// Code generated by "stringer -type=CMD,GET_MSG_KIND,PROTO -output=cons_string.go"; DO NOT EDIT

package comm

import "fmt"

const _CMD_name = "PINGENTERLEAVEPUB"

var _CMD_index = [...]uint8{0, 4, 9, 14, 17}

func (i CMD) String() string {
	i -= 1
	if i >= CMD(len(_CMD_index)-1) {
		return fmt.Sprintf("CMD(%d)", i+1)
	}
	return _CMD_name[_CMD_index[i]:_CMD_index[i+1]]
}

const _GET_MSG_KIND_name = "NOTIFYDISPLAYCONNDATA"

var _GET_MSG_KIND_index = [...]uint8{0, 6, 13, 21}

func (i GET_MSG_KIND) String() string {
	i -= 1
	if i >= GET_MSG_KIND(len(_GET_MSG_KIND_index)-1) {
		return fmt.Sprintf("GET_MSG_KIND(%d)", i+1)
	}
	return _GET_MSG_KIND_name[_GET_MSG_KIND_index[i]:_GET_MSG_KIND_index[i+1]]
}

const _PROTO_name = "TCPHTTPUDP"

var _PROTO_index = [...]uint8{0, 3, 7, 10}

func (i PROTO) String() string {
	i -= 1
	if i < 0 || i >= PROTO(len(_PROTO_index)-1) {
		return fmt.Sprintf("PROTO(%d)", i+1)
	}
	return _PROTO_name[_PROTO_index[i]:_PROTO_index[i+1]]
}
