// Code generated by "stringer -type=CMD,PROTO -output=cons_string.go"; DO NOT EDIT

package cons

import "fmt"

const _CMD_name = "PINGENTERLEAVEPUB"

var _CMD_index = [...]uint8{0, 4, 9, 14, 17}

func (i CMD) String() string {
	i -= 1
	if i >= CMD(len(_CMD_index)-1) {
		return fmt.Sprintf("CMD(%d)", i+1)
	}
	return _CMD_name[_CMD_index[i]:_CMD_index[i+1]]
}

const _PROTO_name = "TCPHTTPUDP"

var _PROTO_index = [...]uint8{0, 3, 7, 10}

func (i PROTO) String() string {
	i -= 1
	if i < 0 || i >= PROTO(len(_PROTO_index)-1) {
		return fmt.Sprintf("PROTO(%d)", i+1)
	}
	return _PROTO_name[_PROTO_index[i]:_PROTO_index[i+1]]
}
